config:
    send_anonymous_usage_stats: False
    use_colors: True

example:
  target: athena
  outputs:

    athena:
      type: athena
      database: "awsdatacatalog"
      region_name: "eu-central-1"
      s3_staging_dir: "s3://paidmedia-tmp-athena/dbt/dev/ahou"
      work_group: "ahou"
      schema:  dbt_athena_external_tables_example
      threads: 1
      retries: 1