config:
    send_anonymous_usage_stats: False
    use_colors: True

example:
  target: athena
  outputs:

    athena:
      type: athena
      database: "{{ env_var('ATHENA_TEST_DBNAME', 'AwsDataCatalog') }}"
      region_name: "{{ env_var('ATHENA_TEST_REGION') }}"
      s3_staging_dir: "s3://{{ env_var('ATHENA_TEST_BUCKET') }}"
      work_group: "{{ env_var('ATHENA_TEST_WORKGROUP', 'primary') }}"
      schema:  dbt_athena_external_tables_example
      threads: 1
      retries: 1