version: 2

sources:
  - name: dbt_athena_external_tables_example
    tables:
      - name: hrsl
        database: awscatalog
        external:
          location: 's3://dataforgood-fb-data/csv/'
          row_format: "SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'"
          serde_properties: "('serialization.format' = '\t\t', 'field.delim' = '\t')"
          table_properties: ('has_encrypted_data'='false')
          hive_compatible_partitions: true
          partitions:
            - name: month
              data_type: string
            - name: country
              data_type: string
            - name: type
              data_type: string
        columns:
          - name: latitude
            data_type: float
          - name: longitude
            data_type: float
          - name: population
            data_type: float

      - name: planet_history
        database: awscatalog
        external:
          location: 's3://osm-pds/planet/'
          file_format: ORCFILE
          comment: "This is a table comment"
        columns:
          - name: id
            data_type: 'BIGINT'
          - name: type
            data_type: 'STRING'
          - name: tags
            data_type: 'MAP<STRING,STRING>'
          - name: lat
            data_type: 'DECIMAL(9,7)'
          - name: lon
            data_type: 'DECIMAL(10,7)'
          - name: nds
            data_type: 'ARRAY<STRUCT<ref: BIGINT>>'
          - name: members
            data_type: 'ARRAY<STRUCT<type: STRING, ref: BIGINT, role: STRING>>'
          - name: changeset
            data_type: 'BIGINT'
          - name: timestamp
            data_type: 'TIMESTAMP'
          - name: uid
            data_type: 'BIGINT'
          - name: user
            data_type: 'STRING'
          - name: version
            data_type: 'BIGINT'
  - name: dbt_analytics_platform_metadata_insights
    tables:
      - name: raw_cloudtrail_event_logs
        database: awscatalog
        external:
          location: 's3://cloudtrail-logs/AWSLogs/YOUR-ACCOUNT-ID/CloudTrail/YOUR-AWS-REGION-1/'
          row_format: "SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'"
          file_format: "INPUTFORMAT 'com.amazon.emr.cloudtrail.CloudTrailInputFormat'"
          output_format: "'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'"
          hive_compatible_partitions: true
          table_properties: ('projection.enabled'='true', 'projection.timestamp.format'='yyyy/MM/dd', 'projection.timestamp.interval'='1', 'projection.timestamp.interval.unit'='DAYS', 'projection.timestamp.range'='2020/01/01,NOW', 'projection.timestamp.type'='date', 'storage.location.template'='s3://cloudtrail-logs/AWSLogs/YOUR-ACCOUNT-ID/CloudTrail/YOUR-AWS-REGION-1//${timestamp}')
          partitions:
            - name: "`timestamp`"
              data_type: STRING
        columns:
          - name: eventversion
            data_type: STRING
          - name: useridentity
            data_type: STRUCT<type:STRING,principalid:STRING,arn:STRING,accountid:STRING,invokedby:STRING,accesskeyid:STRING,username:STRING,onbehalfof:STRUCT<userid:STRING,identitystorearn:STRING>,sessioncontext:STRUCT<attributes:STRUCT<mfaauthenticated:STRING,creationdate:STRING>,sessionissuer:STRUCT<type:STRING,principalid:STRING,arn:STRING,accountid:STRING,username:STRING>,ec2roledelivery:string,webidfederationdata:STRUCT<federatedprovider:STRING,attributes:map<string,string>>>>
          - name: eventtime
            data_type: STRING
          - name: eventsource
            data_type: STRING
          - name: eventname
            data_type: STRING
          - name: awsregion
            data_type: STRING
          - name: sourceipaddress
            data_type: STRING
          - name: useragent
            data_type: STRING
          - name: errorcode
            data_type: STRING
          - name: errormessage
            data_type: STRING
          - name: requestparameters
            data_type: STRING
          - name: responseelements
            data_type: STRING
          - name: additionaleventdata
            data_type: STRING
          - name: requestid
            data_type: STRING
          - name: eventid
            data_type: STRING
          - name: readonly
            data_type: STRING
          - name: resources
            data_type: ARRAY<STRUCT<arn:STRING, accountid:STRING, type:STRING>>
          - name: eventtype
            data_type: STRING
          - name: apiversion
            data_type: STRING
          - name: recipientaccountid
            data_type: STRING
          - name: serviceeventdetails
            data_type: STRING
          - name: sharedeventid
            data_type: STRING
          - name: vpcendpointid
            data_type: STRING
          - name: vpcendpointaccountid
            data_type: STRING
          - name: eventcategory
            data_type: STRING
          - name: addendum
            data_type: STRUCT<reason:STRING, updatedfields:STRING, originalrequestid:STRING, originaleventid:STRING>
          - name: sessioncredentialfromconsole
            data_type: STRING
          - name: edgedevicedetails
            data_type:  STRING
          - name: tlsdetails
            data_type:  STRUCT<tlsversion:STRING, ciphersuite:STRING, clientprovidedhostheader:STRING>
