version: 2

sources:
  - name: dbt_athena_external_tables_example
    tables:
      - name: hrsl
        database: awscatalog
        external:
          location: 's3://dataforgood-fb-data/csv/'
          row_format: "SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'"
          serde_properties: "('serialization.format' = '\t\t', 'field.delim' = '\t')"
          table_properties: ('has_encrypted_data'='false')
          hive_compatible_partitions: true
          partitions:
            - name: month
              data_type: string
            - name: country
              data_type: string
            - name: type
              data_type: string
        columns:
          - name: latitude
            data_type: float
          - name: longitude
            data_type: float
          - name: population
            data_type: float

      - name: planet_history
        database: awscatalog
        external:
          location: 's3://osm-pds/planet/'
          file_format: ORCFILE
          comment: "This is a table comment"
        columns:
          - name: id
            data_type: 'BIGINT'
          - name: type
            data_type: 'STRING'
          - name: tags
            data_type: 'MAP<STRING,STRING>'
          - name: lat
            data_type: 'DECIMAL(9,7)'
          - name: lon
            data_type: 'DECIMAL(10,7)'
          - name: nds
            data_type: 'ARRAY<STRUCT<ref: BIGINT>>'
          - name: members
            data_type: 'ARRAY<STRUCT<type: STRING, ref: BIGINT, role: STRING>>'
          - name: changeset
            data_type: 'BIGINT'
          - name: timestamp
            data_type: 'TIMESTAMP'
          - name: uid
            data_type: 'BIGINT'
          - name: user
            data_type: 'STRING'
          - name: version
            data_type: 'BIGINT'

      - name: aws_public_blockchain
        database: awscatalog
        quoting:
          database: false
          schema: false
          identifier: false
        describe: "https://github.com/aws-samples/digital-assets-examples/blob/main/analytics/"
        external:
          location: "s3://aws-public-blockchain/v1.0"
          row_format: "serde 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'"
          partitions:
            - name: coin
              data_type: string
              path_macro: value_only
              vals: [
                 'btc',
                 'eth'
              ]
            - name: transactions
              data_type: string
              path_macro: value_only
              vals: [
                '/transactions/date=2024-09-19',
                '/transactions/date=2024-09-20'
              ]
        columns:
          - name: gas
            data_type: bigint
          - name: hash
            data_type: string
          - name: input
            data_type: string
          - name: nonce
            data_type: bigint
          - name: value
            data_type: double
          - name: block_number
            data_type: bigint
          - name: block_hash
            data_type: string
          - name: transaction_index
            data_type: bigint
          - name: from_address
            data_type: string
          - name: to_address
            data_type: string
          - name: gas_price
            data_type: bigint
          - name: receipt_cumulative_gas_used
            data_type: bigint
          - name: receipt_gas_used
            data_type: bigint
          - name: receipt_contract_address
            data_type: string
          - name: receipt_status
            data_type: bigint
          - name: receipt_effective_gas_price
            data_type: bigint
          - name: transaction_type
            data_type: int
          - name: max_fee_per_gas
            data_type: bigint
          - name: max_priority_fee_per_gas
            data_type: bigint
          - name: block_timestamp
            data_type: timestamp
          - name: date
            data_type: string
          - name: last_modified
            data_type: timestamp